---
functional:
  - Пользовать должен иметь возможность зарегестироваться и войти в свой аккаунт
  - Во время игры участники должны видеть друг у друга в реальном времени редактор с кодом, вывод тестов
  - Во время решения у пользователя должна быть возможность поменять язык программирования
  - Пользователь должен иметь возможность играть с любым человеком, с ботом или другом (игра будет доступна по ссылке)
  - Пользователь должен иметь возможность выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Пользователь должен иметь возможность выбрать язык (русский или английский), на котором задача будет дана
  - Пользователь должен иметь возможность следить за игрой других пользователей в реальном времени
  - Пользователь должен иметь возможность общаться в чате игры, причем чат доступен только зарегистрированным пользователям
  - Пользователь должен иметь возможность просмотреть завершенную игру в записи. Редактор для ввода кода выглядит как проигрыватель
  - Пользователь должен иметь возможность получить очки за игру, на основе которых строится рейтинг за неделю, месяц и за все время
  - Пользователь должен иметь возможность просмотреть свой профиль (все игры, статистика по играм, имя профиля, аватарка, дата регистрации, статистика по использованным языкам программирования и т.д.)
  - Пользователь должен иметь возможность указать в настройках имя профиля, язык программирования, клан, предпочтения по звукам, ссылки на соц. сети
  - Пользователь должен иметь возможность выйти со своего аккаунта
  - Пользователь должен иметь возможность просмотреть список задач (их название, уровень, тег, источник, состояние, айди и т.д.) и посмотреть определенную задачу
  - Пользователь должен иметь возможность при создании игры выбрать время игры
  - Пользователь должен иметь возможность сброса пароля от аккаунта
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен хранить аккаунт пользователя в сессии браузера
implicit:
  - Сайт должен быть интуитивно понятным и удобным в использовании для пользователя
  - Визуальный дизайн сайта должен быть современным и привлекательным
  - Ошибки при работе с сайтом должны быть обработаны с выводом понятных сообщений пользователю
  - Сайт должен иметь интуитивно понятную и простую навигацию по всем страницам сайта
  - Сайт должен поддерживать все актуальные языки программирования
  - Таймер игры у обоих участников должен начинаться в одно время
  - Зарегистрированный пользователь должен иметь возможность просмотреть таблицу лидерства, запись завершенных игр и статистику
  - Во время игры должен отображаться таймер до конца игры
  - Пользователь должен иметь возможность сдаться во время игры
  - Пользователь должен иметь возможность посмотреть гайд по игре
  - Пользователь должен иметь возможность отправить отзыв (обнаружение бага, предложение улучшения и т.д.)
  - Пользователь должен иметь возможность просмотреть свою статистику и статистику противника
  - Пользователь должен иметь возможность вернуться на главную страницу во время игры
  - Пользователь должен иметь возможность выбрать тему (светлая, темная)
  - Сайт должен оповестить пользователя в случае удачного решения всплывающим сообщением. Также игра должна закончиться
  - В случае неудачного решения игра не должна останавливаться 
